'use strict';

module.exports = {
  LOG_LEVEL_ERROR: 1,
  LOG_LEVEL_WARNING: 2,
  LOG_LEVEL_INFO: 3,
  LOG_LEVEL_DEBUG: 4,
  LOG_LEVEL_TRACE: 5,

  FILE_STATUS_UNCHECKED: 0,
  FILE_STATUS_TO_IGNORE: 1,
  FILE_STATUS_TO_LOAD: 2,
  FILE_STATUS_LOADED: 3
};