'use strict';

module.exports = {
  LOG_LEVEL_ERROR: 1,
  LOG_LEVEL_WARNING: 2,
  LOG_LEVEL_INFO: 3,
  LOG_LEVEL_DEBUG: 4, // Default
  LOG_LEVEL_TRACE: 5,

  LOG_PREFIX: 'fireUp# ',

  FILE_STATUS_UNCHECKED: 0,
  FILE_STATUS_TO_IGNORE: 1,
  FILE_STATUS_TO_LOAD: 2,
  FILE_STATUS_LOADED: 3,
  FILE_STATUS_INVALID: 4,
  FILE_STATUS_REGISTERED: 5,

  MODULE_TYPE_SINGLETON: 'singleton', // Default
  MODULE_TYPE_MULTIPLE_INSTANCES: 'multiple instances'
};